# la politique de Boutique, exportée de nv-01 et relue
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- boutique-front.yaml
- boutique-api.yaml
- boutique-worker.yaml
- boutique-migration.yaml
- postgres.yaml
- redis-cache.yaml
