# postgres.yaml : la politique de nv.postgres.bq-donnees, exportée de nv-01 puis relue
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.postgres.bq-donnees
  namespace: bq-donnees
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - any
    name: external-egress-8
    ports: tcp/443
    priority: 0
    selector:
      comment: ""
      name: external
      original_name: ""
  - action: allow
    applications:
    - DNS
    name: nv.rke2-coredns-rke2-coredns.kube-system-egress-9
    ports: any
    priority: 0
    selector:
      comment: ""
      criteria:
      - key: domain
        op: =
        value: kube-system
      - key: service
        op: =
        value: rke2-coredns-rke2-coredns.kube-system
      name: nv.rke2-coredns-rke2-coredns.kube-system
      original_name: ""
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: bash
    path: /bin/bash
  - action: allow
    allow_update: false
    name: cat
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: grep
    path: /bin/busybox
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: pg_ctl
    path: /usr/local/bin/pg_ctl
  - action: allow
    allow_update: false
    name: pg_dump
    path: /usr/local/bin/pg_dump
  - action: allow
    allow_update: false
    name: postgres
    path: /usr/local/bin/postgres
  - action: allow
    allow_update: false
    name: sh
    path: /bin/busybox
  process_profile:
    baseline: basic
    mode: Protect
  response: null
  target:
    policymode: Protect
    selector:
      comment: ""
      criteria:
      - key: service
        op: =
        value: postgres.bq-donnees
      - key: domain
        op: =
        value: bq-donnees
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: nv.postgres.bq-donnees
      original_name: ""
  waf:
    settings: []
    status: true
