apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-neuvector
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: {{ .Values.vaultServer }}
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: k8s-{{ .Values.clusterName }}
          role: eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
